namespace FileGenerator.Generation
{
    /// <summary>
    /// Random number generator
    /// </summary>
    internal interface IRandomNumberGenerator
    {
        /// <summary>
        /// Generate integer number
        /// </summary>
        /// <param name="min">The least legal value for the Random number</param>
        /// <param name="max">One greater than the greatest legal return value</param>
        /// <returns>Generated number</returns>
        int Generate(int min, int max);
        
        /// <summary>
        /// Generates random array  of bytes
        /// </summary>
        /// <param name="length">Length of array</param>
        /// <returns>Generated bytes</returns>
        byte[] GenerateNextBytes(long length);
    }
}